renamed apitoken commands to token-*
Fixes #15

diff --git a/commands/token-create/script b/commands/token-create/script
--- a/commands/token-create/script
+++ b/commands/token-create/script
@@ -9,15 +9,15 @@
 # The `command` and `usage` comments describe the command
 # and show its options.
 # 
-#/ command: rundeck-admin:apitoken-list: "List the API tokens."
-#/ usage: rerun rundeck-admin:apitoken-list  --password <>  --url <>  --user <> 
+#/ command: rundeck-admin:apitoken-create: "Create an API token."
+#/ usage: rerun rundeck-admin:apitoken-create  --password <admin>  --url <http://localhost:4440>  --user <admin> 
 
 # Load common functions
 # ---------------------
 
 # Load the function library for this module.
 # This loads rerun functions, too.
-. $RERUN_MODULE_DIR/lib/functions.sh apitoken-list || { 
+. $RERUN_MODULE_DIR/lib/functions.sh apitoken-create || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
@@ -29,7 +29,7 @@
 # Trap errors and exit. The call to `rerun_die` will print the
 # the error message and exit with the error command exit status. 
 
-trap 'rerun_die $? "*** command failed: rundeck-admin:apitoken-list. ***"' ERR
+trap 'rerun_die $? "*** command failed: rundeck-admin:apitoken-create. ***"' ERR
 
 # Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
 # so a pipeline return status is the value of the last 
@@ -61,30 +61,26 @@ rerun_options_parse "$@"
 
 # Authenticate
 # ------------
-rundeck_login $URL $USER $PASSWORD
+rundeck_login "$URL" "$USER" "$PASSWORD"
 
+CURL_OUT=$(mktemp -t curl.out.XXXXXXXXXX)
 
-# Get the profile.
-# ----------------
-
-CURL_OUT=$(mktemp "/tmp/curl.out.XXXXX")
-
-
-if ! rundeck_curl -X GET ${URL}/user/profile |
-	(xmlstarlet fo --recover --html --nsclean 2>/dev/null ) |
-	# Get rid of this extraneous class and lang attritues in the html element.		
-	xmlstarlet ed -d "/html[@class]/@class"  |	
-	xmlstarlet ed -d "/html[@lang]/@lang"    > $CURL_OUT
+if ! http_code=$(rundeck_curl -w "%{http_code}" \
+    -H 'Accept: application/xml' \
+    -X POST "${URL}/api/11/tokens/$USER" -o $CURL_OUT 2>/dev/null)
 then
-    rerun_die 3 "API error: ${URL}/user/profile"
+    case ${http_code:-} in
+		* ) rerun_die 3 "API error: POST ${URL}/api/11/tokens/$USER." ;;
+	esac    
+    
 fi
 
 
-# List the tokens.
-if ! xmlstarlet sel -t -m "//span[@class='apitoken']" -v . -n $CURL_OUT
-then
-    :; # no tokens
-fi
+# Print token.
+xmlstarlet sel -t -m //token -v @id -n $CURL_OUT
+
+# Clean up.
+rm $CURL_OUT
 
 # Done. Exit with last command exit status.
 exit $?
