Added apitoken-remove, resource-{add,get} and unit tests.

diff --git a/commands/resource-get/script b/commands/resource-get/script
--- a/commands/resource-get/script
+++ b/commands/resource-get/script
@@ -9,15 +9,15 @@
 # The `command` and `usage` comments describe the command
 # and show its options.
 # 
-#/ command: rundeck-admin:project-export: "export a project"
-#/ usage: rerun rundeck-admin:project-export  --project <>  --url <>  --user <>  --password <> [ --admin <>] 
+#/ command: rundeck-admin:resource-get: "get resource info."
+#/ usage: rerun rundeck-admin:resource-get  --user <>  --password <>  --url <>  --resource <>  --project <> [ --file <>] 
 
 # Load common functions
 # ---------------------
 
 # Load the function library for this module.
 # This loads rerun functions, too.
-. $RERUN_MODULE_DIR/lib/functions.sh project-export || { 
+. $RERUN_MODULE_DIR/lib/functions.sh resource-get || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
@@ -29,7 +29,7 @@
 # Trap errors and exit. The call to `rerun_die` will print the
 # the error message and exit with the error command exit status. 
 
-trap 'rerun_die $? "*** command failed: rundeck:project-export. ***"' ERR
+trap 'rerun_die $? "*** command failed: rundeck-admin:resource-get. ***"' ERR
 
 # Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
 # so a pipeline return status is the value of the last 
@@ -47,7 +47,7 @@ set -o nounset -o pipefail
 # declared by `rerun` or by the option parser function.
 
 #/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option-variables: PROJECT URL USER PASSWORD ARCHIVE
+#/ option-variables: USER PASSWORD URL RESOURCE FORMAT PROJECT FILE
 
 # The `rerun_options_parse` function processes the command line
 # arguments. Each accepted command line flag results in setting 
@@ -59,31 +59,61 @@ rerun_options_parse "$@"
 # Command implementation
 # ----------------------
 
+: ${FORMAT:=xml}
+case $FORMAT in
+    xml|yaml) ;;
+    *) rerun_die 2 "invalid argument. --format <xml|yaml>"
+esac
+
 # - - -
 # Put the command implementation here.
 # - - -
 
 CURLOPTS="-k -f -s -S -L -c cookies -b cookies"
 CURL="curl $CURLOPTS"
-CURL_OUT=$(mktemp -t curl.out.XXXXXXXXXX)
-    
-# Authenticate
+
+CURL_OUT=$(mktemp "/tmp/curl.out.XXXXX")
+
+
+
+# Authenticate.
 loginurl="${URL}/j_security_check"
-$CURL $loginurl > $CURL_OUT
-$CURL -X POST -d j_username=${USER} -d j_password=${PASSWORD} $loginurl > $CURL_OUT
+$CURL $loginurl > /dev/null
+$CURL -d j_username=${USER} -d j_password=${PASSWORD} -X POST $loginurl > /dev/null
 
-# Export
-exporturl="${URL}/project/export"
-: ${ARCHIVE:=${PROJECT}.zip}
-$CURL -X GET $exporturl/export?name=$PROJECT > $ARCHIVE
+# Get the resources for the project.
+APIURL="${URL}/api/3/resource/$RESOURCE?project=${PROJECT}&format=${FORMAT}"
+$CURL -o $CURL_OUT -X GET $APIURL
 
-if [ ! -f $ARCHIVE ]
-then
-    echo >&2 "Unexpected error. Archive file not found after export request"
-    exit 1
+# Check if the result is an xml file.
+# It might be valid xml containing api error information.
+# Fail the command if the api returned an error.
+
+if ! xmlstarlet val -q $CURL_OUT
+then :;# do nothing. it's not xml.
+else
+    # it's xml. check if it has an api result.
+    if ! error=$(xmlstarlet sel -t -m "/result" -v @error $CURL_OUT)
+    then :;# do nothing. it is not a result xml.
+    else
+        # fail the command if the api returned an error.
+        [ "$error" = "true" ] && {
+            rerun_die 3 $(xmlstarlet sel -t -m "/result/error" -v message $CURL_OUT)
+        }
+    fi
 fi
 
-echo >&2 "Project exported to archive: $ARCHIVE"
+#
+# Store the results in the specified file otherwise write it to stdout.
+#
+if [ -n "$FILE" ]
+then cp  $CURL_OUT $FILE
+else cat $CURL_OUT
+fi
+
+# Clean up temp file.
+rm $CURL_OUT
+
 
 # Done. Exit with last command exit status.
 exit $?
